# Generated by Django 3.1.2 on 2020-10-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201021_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SongArtistRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.song')),
            ],
        ),
        migrations.CreateModel(
            name='SongAlbumRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.album')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.song')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumArtistRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.album')),
            ],
        ),
    ]
